name: Automatically trigger a GitHub Actions workflow by Pushing code to main branch.

on:
  push:
    branches:
      - main

jobs:
  experiment_train:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job-cluster-dev.yml  --stream -s --resource-group mlops --workspace-name mlops_getting_started

  production_train:
    runs-on: ubuntu-latest
    environment: development
    needs: ["experiment_train"]
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job-cluster-prod.yml --stream -s --resource-group mlops --workspace-name mlops_getting_started