name: Manually trigger a GitHub Actions workflow to Deploy Latest Version of Model.

on:
  workflow_dispatch:

jobs:
  create-endpoint:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create Endpoint
      run: |
         az ml online-endpoint create --name diabetest-prod-pred --file src/create-endpoint.yml --resource-group mlops --workspace-name mlops_getting_started


  deploy-model:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job-cluster-dev.yml  --stream -s --resource-group mlops --workspace-name mlops_getting_started
